# Generated by Django 5.2.3 on 2025-06-27 09:03

import django.db.models.deletion
import safe_filefield.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_note_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', safe_filefield.models.SafeFileField(upload_to='filess/', verbose_name='File')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.note', verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Note File',
                'verbose_name_plural': 'Note Files',
            },
        ),
    ]
